"use client"
import Head from 'next/head';
import React from 'react';
import Slider from 'react-slick';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import SliderCard from '../SliderCard/SliderCard';

export default function Featured() {
const settings = {
  dots: true,
  infinite: true,
  speed: 500,
  slidesToShow: 5,
  slidesToScroll: 1,
  autoplay: true,
  autoplaySpeed: 3000,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 1,
        infinite: true,
        dots: true,
      }
    },
    {
      breakpoint: 768,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
        infinite: true,
        dots: true,
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
        infinite: true,
        dots: true,
      }
    }
  ]
};

  return (
    <div>
<Head>
  <title>My Slider App</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head>

<main className="flex flex-col items-center mt-[-170px] justify-center min-h-screen py-2 bg-gray-100">
  <h1 className="text-4xl font-bold mb-8">Featured Vendors</h1>
  <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.</p>
  <div className="w-full max-w-6xl">
    <Slider {...settings}>
      <div>
        <SliderCard />
      </div>
      <div>
        <SliderCard />
      </div>
      <div>
        <SliderCard />
      </div>
      <div>
        <SliderCard />
      </div>
      <div>
        <SliderCard />
      </div>
      <div>
        <SliderCard />
      </div>
      <div>
        <SliderCard />
      </div>
    </Slider>
  </div>
</main>
    </div>
  );
}